# Generated by Django 3.1.5 on 2021-01-05 16:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='sunojan-saha/image'),
        ),
    ]
