# Generated by Django 3.1.5 on 2021-01-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210105_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='tel',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
