# Generated by Django 3.1.5 on 2021-01-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_infopage_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='tel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
